SHELL = /bin/sh

include ../paths.sh

install:
	mkdir -p $(HTDOCSDIR)/scl/amarakosha; mkdir -p $(CGIDIR)/scl/amarakosha; cp web_interface/*.html $(HTDOCSDIR)/scl/amarakosha; cp -r web_interface/FAQ $(HTDOCSDIR)/scl/amarakosha/; cp -r web_interface/*.cgi $(CGIDIR)/scl/amarakosha; cp web_interface/amarakosha_knowledge_structure.pdf $(HTDOCSDIR)/scl/amarakosha; cp web_interface/logouoh.png $(HTDOCSDIR)/scl/amarakosha; cp web_interface/about.html $(HTDOCSDIR)/scl/amarakosha; 
