SHELL = /bin/sh

include ../../paths.sh
install:
	mkdir -p $(HTDOCSDIR)/$(SCL_HTDOCS)/e-readers/sbg; mkdir -p $(CGIDIR)/$(SCL_CGI)/e-readers/sbg
	cp -r 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 $(HTDOCSDIR)/$(SCL_HTDOCS)/e-readers/sbg
	cp -r js_files/* css_files/* images $(HTDOCSDIR)/$(SCL_HTDOCS)/e-readers/sbg
	cp  *.html  $(HTDOCSDIR)/$(SCL_HTDOCS)/e-readers/sbg
