SHELL = /bin/sh

include ../../paths.sh
install:
	mkdir -p $(HTDOCSDIR)/scl/e-readers/sbg; mkdir -p $(CGIDIR)/scl/e-readers/sbg
	cp -r 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 $(HTDOCSDIR)/scl/e-readers/sbg
	cp -r js_files/* css_files/* images $(HTDOCSDIR)/scl/e-readers/sbg
	cp  *.html  $(HTDOCSDIR)/scl/e-readers/sbg
	cp  cgi_files/* $(CGIDIR)/scl/e-readers/sbg
