SHELL = /bin/sh

include ../paths.sh

install:
	mkdir -p $(HTDOCSDIR)/scl/transliteration; mkdir -p $(CGIDIR)/scl/transliteration; cp *.html $(HTDOCSDIR)/scl/transliteration; cp *.cgi $(CGIDIR)/scl/transliteration;
