SHELL = /bin/sh

include ../paths.sh

install:
	mkdir -p $(HTDOCSDIR)/scl/transliteration; mkdir -p $(CGIDIR)/scl/transliteration; cp *.html $(HTDOCSDIR)/scl/transliteration; cp *.cgi $(CGIDIR)/scl/transliteration;

debian_install:
	mkdir -p /tmp/scl$(HTDOCSDIR)/scl/transliteration; mkdir -p /tmp/scl$(CGIDIR)/scl/transliteration; cp *.html /tmp/scl$(HTDOCSDIR)/scl/transliteration; cp  *.js /tmp/scl$(HTDOCSDIR)/scl/transliteration;   cp *.cgi /tmp/scl$(CGIDIR)/scl/transliteration; cp table.html /tmp/scl$(HTDOCSDIR)/scl/transliteration; /tmp/scl$(HTDOCSDIR)/scl/transliteration/;
