SHELL = /bin/sh

include ../paths.sh

install:
	mkdir -p $(HTDOCSDIR)/$(SCL_HTDOCS)/transliteration; mkdir -p $(CGIDIR)/$(SCL_CGI)/transliteration; cp *.html $(HTDOCSDIR)/$(SCL_HTDOCS)/transliteration; cp *.cgi $(CGIDIR)/$(SCL_CGI)/transliteration;
