/*
*/
#include "../headers/all_purpose.h"
#include "../headers/mydefs.h"
struct verb_correction verb_future_list[]={
/* no_of_chars rep_str */
{0,"UzgA"}, /* KAUzgA */
{0,"egA"}, /* KAegA */
{0,"iegA"}, /* KAiegA */
{0,"egA"}, /* KAegA */
{0,"ezge"}, /* KAezge */
{0,"oge"}, /* KAoge */
{0,"iegA"}, /* KAiegA */
{0,"ezge"}, /* KAezge */
{0,"UzgI"}, /* KAUzgI */
{0,"egI"}, /* KAegI */
{0,"iegA"}, /* KAiegA */
{0,"egI"}, /* KAegI */
{0,"ezgI"}, /* KAezgI */
{0,"ogI"}, /* KAogI */
{0,"iegA"}, /* KAiegA */
{0,"ezgI"}, /* KAezgI */
{1,"UzgA"}, /* karUzgA */
{1,"egA"}, /* karegA */
{3,"IjiyegA"}, /* kIjiyegA */
{1,"egA"}, /* karegA */
{1,"eMge"}, /* kareMge */
{1,"oge"}, /* karoge */
{3,"IjiyegA"}, /* kIjiyegA */
{1,"eMge"}, /* kareMge */
{1,"UzgI"}, /* karUzgI */
{1,"egI"}, /* karegI */
{3,"IjiyegA"}, /* kIjiyegA */
{1,"egI"}, /* karegI */
{1,"eMgI"}, /* kareMgI */
{1,"ogI"}, /* karogI */
{3,"IjiyegA"}, /* kIjiyegA */
{1,"eMgI"}, /* kareMgI */
{1,"UzgA"}, /* lUzgA */
{0,"gA"}, /* legA */
{1,"IjiyegA"}, /* lIjiyegA */
{0,"gA"}, /* legA */
{0,"Mge"}, /* leMge */
{1,"oge"}, /* loge */
{1,"IjiyegA"}, /* lIjiyegA */
{0,"Mge"}, /* leMge */
{1,"UzgI"}, /* lUzgI */
{0,"gI"}, /* legI */
{1,"IjiyegA"}, /* lIjiyegA */
{0,"gI"}, /* legI */
{0,"MgI"}, /* leMgI */
{1,"ogI"}, /* logI */
{1,"IjiyegA"}, /* lIjiyegA */
{0,"MgI"}, /* leMgI */
{0,"UzgA"}, /* hoUzgA */
{0,"gA"}, /* hogA */
{0,"iyegA"}, /* hoiyegA */
{0,"gA"}, /* hogA */
{0,"Mge"}, /* hoMge */
{0,"ge"}, /* hoge */
{0,"iyegA"}, /* hoiyegA */
{0,"Mge"}, /* hoMge */
{0,"UzgI"}, /* hoUzgI */
{0,"gI"}, /* hogI */
{0,"iyegA"}, /* hoiyegA */
{0,"gI"}, /* hogI */
{0,"MgI"}, /* hoMgI */
{0,"ogI"}, /* hoogI */
{0,"iyegA"}, /* hoiyegA */
{0,"MgI"}, /* hoMgI */
{1,"iUzgA"}, /* piUzgA */
{1,"iegA"}, /* piegA */
{0,"jiegA"}, /* pIjiegA */
{1,"iegA"}, /* piegA */
{1,"iezge"}, /* piezge */
{1,"ioge"}, /* pioge */
{0,"jiegA"}, /* pIjiegA */
{1,"iezge"}, /* piezge */
{1,"iUzgI"}, /* piUzgI */
{1,"iyegI"}, /* piyegI */
{0,"jiegA"}, /* pIjiegA */
{1,"iyegI"}, /* piyegI */
{1,"iezgI"}, /* piezgI */
{1,"iogI"}, /* piogI */
{0,"jiegA"}, /* pIjiegA */
{1,"iezgI"}, /* piezgI */
{1,"uUzgA"}, /* CuUzgA */
{1,"uegA"}, /* CuegA */
{1,"uiegA"}, /* CuiegA */
{1,"uegA"}, /* CuegA */
{1,"uezge"}, /* Cuezge */
{1,"uoge"}, /* Cuoge */
{1,"uiegA"}, /* CuiegA */
{1,"uezge"}, /* Cuezge */
{1,"uUzgI"}, /* CuUzgI */
{1,"uegI"}, /* CuegI */
{1,"uiegA"}, /* CuiegA */
{1,"uegI"}, /* CuegI */
{1,"uezgI"}, /* CuezgI */
{1,"uogI"}, /* CuogI */
{1,"uiegA"}, /* CuiegA */
{1,"uezgI"}, /* CuezgI */
{1,"UzgA"}, /* uTUzgA */
{1,"egA"}, /* uTegA */
{1,"iegA"}, /* uTiegA */
{1,"egA"}, /* uTegA */
{1,"eMge"}, /* uTeMge */
{1,"oge"}, /* uToge */
{1,"iegA"}, /* uTiegA */
{1,"eMge"}, /* uTeMge */
{1,"UzgI"}, /* uTUzgI */
{1,"egI"}, /* uTegI */
{1,"iegA"}, /* uTiegA */
{1,"egI"}, /* uTegI */
{1,"eMgI"}, /* uTeMgI */
{1,"ogI"}, /* uTogI */
{1,"iegA"}, /* uTiegA */
{1,"eMgI"}, /* uTeMgI */
{0,"UzgA"}, /* soUzgA */
{0,"egA"}, /* soegA */
{0,"iegA"}, /* soiegA */
{0,"egA"}, /* soegA */
{0,"yeMge"}, /* soyeMge */
{0,"oge"}, /* sooge */
{0,"iegA"}, /* soiegA */
{0,"yeMge"}, /* soyeMge */
{0,"UzgI"}, /* soUzgI */
{0,"yegI"}, /* soyegI */
{0,"iegA"}, /* soiegA */
{0,"yegI"}, /* soyegI */
{0,"yeMgI"}, /* soyeMgI */
{0,"ogI"}, /* soogI */
{0,"iegA"}, /* soiegA */
{0,"yeMgI"} /* soyeMgI */
};
