#include "../headers/all_purpose.h"
#include "../headers/mydefs.h"
struct verb_correction verb_subj_list[]={
/* no_of_chars rep_str */
{0,"Uz"}, /* KAUz */
{0,"ye"}, /* KAye */
{0,"iye"}, /* KAiye */
{0,"ye"}, /* KAye */
{0,"yeM"}, /* KAyeM */
{0,"o"}, /* KAo */
{0,"iye"}, /* KAiye */
{0,"yeM"}, /* KAyeM */
{1,"Uz"}, /* karUz */
{1,"e"}, /* kare */
{1,"ie"}, /* karie */
{1,"e"}, /* kare */
{1,"eM"}, /* kareM */
{1,"o"}, /* karo */
{1,"eM"}, /* kareM */
{1,"ie"}, /* karie */
{1,"Uz"}, /* lUz */
{0,""}, /* le */
{1,"Ijie"}, /* lIjie */
{0,""}, /* le */
{0,"M"}, /* leM */
{1,"o"}, /* lo */
{1,"Ijie"}, /* lIjie */
{0,"M"}, /* leM */
{0,"Uz"}, /* hoUz */
{0,""}, /* ho */
{0,"ie"}, /* hoie */
{0,""}, /* ho */
{0,"yeM"}, /* hoyeM */
{0,"o"}, /* hoo */
{0,"ie"}, /* hoie */
{0,"yeM"}, /* hoyeM */
{1,"iUz"}, /* piUz */
{1,"iye"}, /* piye */
{0,"jiye"}, /* pIjiye */
{1,"iye"}, /* piye */
{1,"iyeM"}, /* piyeM */
{1,"io"}, /* pio */
{0,"jiye"}, /* pIjiye */
{1,"iyeM"}, /* piyeM */
{1,"uUz"}, /* CuUz */
{1,"uye"}, /* Cuye */
{1,"uiye"}, /* Cuiye */
{1,"uye"}, /* Cuye */
{1,"uyeM"}, /* CuyeM */
{1,"uo"}, /* Cuo */
{1,"uiye"}, /* Cuiye */
{1,"uyeM"}, /* CuyeM */
{1,"Uz"}, /* uTUz */
{1,"e"}, /* uTe */
{1,"ie"}, /* uTie */
{1,"e"}, /* uTe */
{1,"eM"}, /* uTeM */
{1,"o"}, /* uTo */
{1,"ie"}, /* uTie */
{1,"eM"}, /* uTeM */
{0,"Uz"}, /* soUz */
{0,""}, /* so */
{0,"ie"}, /* soie */
{0,"e"}, /* soe */
{0,"yeM"}, /* soyeM */
{0,"o"}, /* soo */
{0,"ie"}, /* soie */
{0,"yeM"} /* soyeM */
};
