SHELL = /bin/bash

include ../paths.sh

install:
	cp *.html $(HTDOCSDIR)/scl; cp *.js $(HTDOCSDIR)/scl; cp -r ../css_files $(HTDOCSDIR)/scl; cp -r ../js_files $(HTDOCSDIR)/scl; cp -r ../imgs $(HTDOCSDIR)/scl; cp *.cgi $(CGIDIR)/scl
