SHELL = /bin/bash

include ../../../paths.sh

install:
	mkdir -p $(CGIDIR)/$(SCL_CGI)/MT/prog/kAraka/Prepare_Graph/DATA/AkAfkRA
	mkdir -p $(CGIDIR)/$(SCL_CGI)/MT/prog/kAraka/list_n
	cp shabdabodha.sh $(CGIDIR)/$(SCL_CGI)/MT/prog/kAraka/
	cp Prepare_Graph/build_graph $(CGIDIR)/$(SCL_CGI)/MT/prog/kAraka/Prepare_Graph
	cp uniform_morph_anal.pl $(CGIDIR)/$(SCL_CGI)/MT/prog/kAraka/
	cp kaaraka_sharing.pl $(CGIDIR)/$(SCL_CGI)/MT/prog/kAraka/
	cp add_best_parse_output.pl $(CGIDIR)/$(SCL_CGI)/MT/prog/kAraka/
	cp add_abhihita_info.pl $(CGIDIR)/$(SCL_CGI)/MT/prog/kAraka/
	cp add_possible_relations.pl $(CGIDIR)/$(SCL_CGI)/MT/prog/kAraka/
	cp add_hidden_sub_gen.pl $(CGIDIR)/$(SCL_CGI)/MT/prog/kAraka/
	cp handle_no_parse.pl $(CGIDIR)/$(SCL_CGI)/MT/prog/kAraka/
	cp mk_summary.pl $(CGIDIR)/$(SCL_CGI)/MT/prog/kAraka/
	cp draw_graph_gen.pl $(CGIDIR)/$(SCL_CGI)/MT/prog/kAraka/
	cp Prepare_Graph/DATA/AkAfkRA/relations.txt $(CGIDIR)/$(SCL_CGI)/MT/prog/kAraka/Prepare_Graph/DATA/AkAfkRA
	cp list_n/kAraka_names_*.txt $(CGIDIR)/$(SCL_CGI)/MT/prog/kAraka/list_n/
