SHELL = /bin/bash

include ../paths.sh

install:
	mkdir -p $(HTDOCSDIR)/$(SCL_HTDOCS)/YMK; mkdir -p $(CGIDIR)/$(SCL_CGI)/YMK; cp *.html $(HTDOCSDIR)/$(SCL_HTDOCS)/YMK/; cp *.cgi $(CGIDIR)/$(SCL_CGI)/YMK/; cp *.py $(CGIDIR)/$(SCL_CGI)/YMK/
#sh install.sh cgi $(CGIDIR)/$(SCL_CGI)/YMK
